# Template C++ Application

# This template allows you to validate your C++ application.
# The workflow allows running tests and code linting on the default branch.


image: pyguerder/bitbucket-pipelines-php72

pipelines:
  default:
    - step:
        script: # Modify the commands below to build your repository.
        
          - apt update && apt upgrade -y 
          - sudo apt-get install build-essential git cmake libboost-all-dev libreadline-dev -y
          - mkdir build
          - cd build
          - cmake ..
          - cd ..
          - make