# Template C++ Application

# This template allows you to validate your C++ application.
# The workflow allows running tests and code linting on the default branch.


image: gcc:6.1
pipelines:
  default:
    - step:
        script: # Modify the commands below to build your repository.
          - mkdir build
          - cd build
          - cmake ..
          - cd ..
          - make